title: "Master Eye Security"
email: mastereyeservices@gmail.com

timezone: UTC
url: 'https://mastereyesecurityservicesltd.com.ng'
permalink: "/:title/"
logo: 'assets/images/IMG-20230221-WA0004.jpg'
favicon: 'assets/images/IMG-20230221-WA0004.jpg'
author: Mr John Inalegwu
paginate: 6
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Master Eye Security
    display_name: Master Eye Security
    avatar: 'assets/images/IMG-20230221-WA0004.jpg'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John Inalegwu
    display_name: John Inalegwu
    avatar: 'assets/images/IMG-20230225-WA00031.jpg'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  whatsapp: tel:07062094716
  facebook: https://www.facebook.com/profile.php?id=100083360731755&mibextid=ZbWKwL
  linkedin: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives


